#:schema ../../api/generated/word.json
id = "inuka"
author_verbatim = ".. inuka inuka -
(content word)
1. smell, scent, sniff, detect, notice"
author_verbatim_source = "https://discord.com/channels/301377942062366741/545467374254555137/793623130748092456"
book = "none"
coined_era = "post-pu"
coined_year = "2020"
creator = ["kule epiku Atawan"]
see_also = ["nena", "pilin"]
source_language = ""
usage_category = "sandbox"
word = "inuka"
deprecated = false
audio = []

[[etymology]]
word = ""

[usage]
