#:schema ../../api/generated/word.json
id = "tenki"
author_verbatim = ""
author_verbatim_source = ""
book = "none"
coined_era = "post-pu"
coined_year = "2020"
creator = ["kule epiku Atawan"]
see_also = ["wawa"]
source_language = "Japanese"
usage_category = "sandbox"
word = "tenki"
deprecated = false
audio = []

[[etymology]]
alt = "denki"
word = "電気"

[usage]
